/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'player' : Player,
  'totalGrossScore' : bigint,
}
export interface Player {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'handicap' : bigint,
}
export interface Score {
  'id' : string,
  'hole' : bigint,
  'playerId' : string,
  'createdAt' : Time,
  'tournamentId' : string,
  'strokes' : bigint,
}
export type Time = bigint;
export interface Tournament {
  'id' : string,
  'status' : TournamentStatus,
  'date' : Time,
  'name' : string,
  'createdAt' : Time,
  'location' : string,
  'format' : TournamentFormat,
}
export type TournamentFormat = { 'matchPlay' : null } |
  { 'stableford' : null } |
  { 'strokePlay' : null };
export type TournamentStatus = { 'upcoming' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface _SERVICE {
  'createPlayer' : ActorMethod<[string, string, bigint], undefined>,
  'createTournament' : ActorMethod<
    [string, string, Time, TournamentFormat, string],
    undefined
  >,
  'deletePlayer' : ActorMethod<[string], undefined>,
  'deleteTournament' : ActorMethod<[string], undefined>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getPlayer' : ActorMethod<[string], Player>,
  'getPlayersForTournament' : ActorMethod<[string], Array<Player>>,
  'getScoresForPlayer' : ActorMethod<[string, string], Array<Score>>,
  'getTournament' : ActorMethod<[string], Tournament>,
  'getTournamentLeaderboard' : ActorMethod<[string], Array<LeaderboardEntry>>,
  'getTournamentsForPlayer' : ActorMethod<[string], Array<Tournament>>,
  'recordScore' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'registerPlayerToTournament' : ActorMethod<[string, string], undefined>,
  'removePlayerFromTournament' : ActorMethod<[string, string], undefined>,
  'updatePlayer' : ActorMethod<
    [string, [] | [string], [] | [bigint]],
    undefined
  >,
  'updateTournament' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [Time],
      [] | [TournamentFormat],
      [] | [TournamentStatus],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];