/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TournamentFormat = IDL.Variant({
  'matchPlay' : IDL.Null,
  'stableford' : IDL.Null,
  'strokePlay' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'handicap' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'status' : TournamentStatus,
  'date' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'location' : IDL.Text,
  'format' : TournamentFormat,
});
export const Score = IDL.Record({
  'id' : IDL.Text,
  'hole' : IDL.Nat,
  'playerId' : IDL.Text,
  'createdAt' : Time,
  'tournamentId' : IDL.Text,
  'strokes' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'player' : Player,
  'totalGrossScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createTournament' : IDL.Func(
      [IDL.Text, IDL.Text, Time, TournamentFormat, IDL.Text],
      [],
      [],
    ),
  'deletePlayer' : IDL.Func([IDL.Text], [], []),
  'deleteTournament' : IDL.Func([IDL.Text], [], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getPlayer' : IDL.Func([IDL.Text], [Player], ['query']),
  'getPlayersForTournament' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'getScoresForPlayer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Score)],
      ['query'],
    ),
  'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
  'getTournamentLeaderboard' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTournamentsForPlayer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Tournament)],
      ['query'],
    ),
  'recordScore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'registerPlayerToTournament' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removePlayerFromTournament' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePlayer' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(TournamentFormat),
        IDL.Opt(TournamentStatus),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TournamentFormat = IDL.Variant({
    'matchPlay' : IDL.Null,
    'stableford' : IDL.Null,
    'strokePlay' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'handicap' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'status' : TournamentStatus,
    'date' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'location' : IDL.Text,
    'format' : TournamentFormat,
  });
  const Score = IDL.Record({
    'id' : IDL.Text,
    'hole' : IDL.Nat,
    'playerId' : IDL.Text,
    'createdAt' : Time,
    'tournamentId' : IDL.Text,
    'strokes' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'player' : Player,
    'totalGrossScore' : IDL.Nat,
  });
  
  return IDL.Service({
    'createPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Text, Time, TournamentFormat, IDL.Text],
        [],
        [],
      ),
    'deletePlayer' : IDL.Func([IDL.Text], [], []),
    'deleteTournament' : IDL.Func([IDL.Text], [], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getPlayer' : IDL.Func([IDL.Text], [Player], ['query']),
    'getPlayersForTournament' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getScoresForPlayer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Score)],
        ['query'],
      ),
    'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
    'getTournamentLeaderboard' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTournamentsForPlayer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Tournament)],
        ['query'],
      ),
    'recordScore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'registerPlayerToTournament' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removePlayerFromTournament' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePlayer' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(TournamentFormat),
          IDL.Opt(TournamentStatus),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };