/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: string;
    name: string;
    createdAt: Time;
    handicap: bigint;
}
export interface LeaderboardEntry {
    player: Player;
    totalGrossScore: bigint;
}
export type Time = bigint;
export interface Score {
    id: string;
    hole: bigint;
    playerId: string;
    createdAt: Time;
    tournamentId: string;
    strokes: bigint;
}
export interface Tournament {
    id: string;
    status: TournamentStatus;
    date: Time;
    name: string;
    createdAt: Time;
    location: string;
    format: TournamentFormat;
}
export enum TournamentFormat {
    matchPlay = "matchPlay",
    stableford = "stableford",
    strokePlay = "strokePlay"
}
export enum TournamentStatus {
    upcoming = "upcoming",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    createPlayer(id: string, name: string, handicap: bigint): Promise<void>;
    createTournament(id: string, name: string, date: Time, format: TournamentFormat, location: string): Promise<void>;
    deletePlayer(id: string): Promise<void>;
    deleteTournament(id: string): Promise<void>;
    getAllPlayers(): Promise<Array<Player>>;
    getAllTournaments(): Promise<Array<Tournament>>;
    getPlayer(id: string): Promise<Player>;
    getPlayersForTournament(tournamentId: string): Promise<Array<Player>>;
    getScoresForPlayer(tournamentId: string, playerId: string): Promise<Array<Score>>;
    getTournament(id: string): Promise<Tournament>;
    getTournamentLeaderboard(tournamentId: string): Promise<Array<LeaderboardEntry>>;
    getTournamentsForPlayer(playerId: string): Promise<Array<Tournament>>;
    recordScore(id: string, tournamentId: string, playerId: string, hole: bigint, strokes: bigint): Promise<void>;
    registerPlayerToTournament(tournamentId: string, playerId: string): Promise<void>;
    removePlayerFromTournament(tournamentId: string, playerId: string): Promise<void>;
    updatePlayer(id: string, name: string | null, handicap: bigint | null): Promise<void>;
    updateTournament(id: string, name: string | null, date: Time | null, format: TournamentFormat | null, status: TournamentStatus | null, location: string | null): Promise<void>;
}
import type { Time as _Time, Tournament as _Tournament, TournamentFormat as _TournamentFormat, TournamentStatus as _TournamentStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPlayer(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0, arg1, arg2);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: string, arg2: Time, arg3: TournamentFormat, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, to_candid_TournamentFormat_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, to_candid_TournamentFormat_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deletePlayer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async deleteTournament(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0);
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return result;
        }
    }
    async getAllTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: string): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return result;
        }
    }
    async getPlayersForTournament(arg0: string): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersForTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersForTournament(arg0);
            return result;
        }
    }
    async getScoresForPlayer(arg0: string, arg1: string): Promise<Array<Score>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoresForPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoresForPlayer(arg0, arg1);
            return result;
        }
    }
    async getTournament(arg0: string): Promise<Tournament> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_Tournament_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_Tournament_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentLeaderboard(arg0: string): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentLeaderboard(arg0);
            return result;
        }
    }
    async getTournamentsForPlayer(arg0: string): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentsForPlayer(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentsForPlayer(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordScore(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordScore(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordScore(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async registerPlayerToTournament(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPlayerToTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPlayerToTournament(arg0, arg1);
            return result;
        }
    }
    async removePlayerFromTournament(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayerFromTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayerFromTournament(arg0, arg1);
            return result;
        }
    }
    async updatePlayer(arg0: string, arg1: string | null, arg2: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTournament(arg0: string, arg1: string | null, arg2: Time | null, arg3: TournamentFormat | null, arg4: TournamentStatus | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournament(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournament(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_TournamentFormat_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentFormat): TournamentFormat {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TournamentStatus;
    date: _Time;
    name: string;
    createdAt: _Time;
    location: string;
    format: _TournamentFormat;
}): {
    id: string;
    status: TournamentStatus;
    date: Time;
    name: string;
    createdAt: Time;
    location: string;
    format: TournamentFormat;
} {
    return {
        id: value.id,
        status: from_candid_TournamentStatus_n6(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        location: value.location,
        format: from_candid_TournamentFormat_n8(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TournamentStatus {
    return "upcoming" in value ? TournamentStatus.upcoming : "completed" in value ? TournamentStatus.completed : "inProgress" in value ? TournamentStatus.inProgress : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchPlay: null;
} | {
    stableford: null;
} | {
    strokePlay: null;
}): TournamentFormat {
    return "matchPlay" in value ? TournamentFormat.matchPlay : "stableford" in value ? TournamentFormat.stableford : "strokePlay" in value ? TournamentFormat.strokePlay : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n4(_uploadFile, _downloadFile, x));
}
function to_candid_TournamentFormat_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentFormat): _TournamentFormat {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): _TournamentStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentFormat | null): [] | [_TournamentFormat] {
    return value === null ? candid_none() : candid_some(to_candid_TournamentFormat_n1(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus | null): [] | [_TournamentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_TournamentStatus_n15(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): {
    upcoming: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TournamentStatus.upcoming ? {
        upcoming: null
    } : value == TournamentStatus.completed ? {
        completed: null
    } : value == TournamentStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentFormat): {
    matchPlay: null;
} | {
    stableford: null;
} | {
    strokePlay: null;
} {
    return value == TournamentFormat.matchPlay ? {
        matchPlay: null
    } : value == TournamentFormat.stableford ? {
        stableford: null
    } : value == TournamentFormat.strokePlay ? {
        strokePlay: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
